# Generated by Django 4.1.4 on 2023-01-18 15:14

from django.db import migrations, models

import app.user.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_company_options_alter_company_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="available_tables",
            field=app.user.fields.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("parts", "Parts"),
                        ("manufacturers", "Manufacturers"),
                        ("quotes", "Part Quotes"),
                    ],
                    max_length=13,
                ),
                blank=True,
                default=list,
                null=True,
                size=3,
            ),
        ),
    ]
