# Generated by Django 4.1.4 on 2023-01-18 15:53

from django.db import migrations, models

import app.user.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_company_available_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="available_tables",
            field=app.user.fields.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("part", "Parts"),
                        ("manufacturer", "Manufacturers"),
                        ("partquote", "Part Quotes"),
                    ],
                    max_length=13,
                ),
                blank=True,
                default=list,
                null=True,
                size=3,
            ),
        ),
    ]
